### ISSUE TITLE
Mouse dob and father and mother should be constructed from database

### ISSUE THREAD

**Issue by cxrodgers** [cxrodgers/MouseColony#9]
Instead of manually specifying these fields, they should be calculated and reported by a class method that traverses to "litter" and "breeding_cage" to identify this info. But we also need a way to manually specify it for mice that have been grandfathered into the system, or were bought from Jackson, or for any other reason that that info might not be available.

**Comment by danieldkato** [comment]
One way to do this would be to include mother and father as normal foreign key fields of Mouse. Then, in LitterAdmin, we could customize the save_model() method (which is already built in to the ModelAdmin class) so that whenever the user presses the "save" button, the method traverses "breeding_cage", gets the parents and assigns them to the mother and father fields of each of the litter's individual mouse instances.  

This way, mother and father will automatically be assigned whenever a mouse is added to a litter, but the mother and father fields themselves can be manually edited (or left blank) by the user from the MouseAdmin change page if litter info isn't available for whatever reason.

**Comment by danieldkato** [comment]
Also, for the sake of concision, father and mother can be ommitted from the MouseInline so that individual mice added to a litter don't display them.

**Comment by cxrodgers** [comment]
Commit eacf242c828b1b2ceff7dc998420c782e4002f56 implements this. Actually I removed the logic to automatically save the mouse DOB with the litter DOB. The problem is that if the litter DOB is changed later, the mouse DOB needs to automatically update.

Instead I implemented a manual_DOB field which is only set when necessary (eg, no litter available). The dob field is now a simple property that traverses litter.dob if available and otherwise returns manual_DOB. Same deal with father and mother.
